name: build documentation with mkdocs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build and deploy mkdocs
    runs-on: ubuntu-latest
    steps:
      - name: checkout main 
        uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U git+https://github.com/mkdocs/mkdocs.git#egg=mkdocs
          pip install mkdocs-material
      - name: deploy
        run: |
          git pull origin main
          mkdocs gh-deploy --force
          mkdocs --version
